const permissions = {
  CREATE_TOKEN_ISSUER: 'Create Token Issuer',
  CREATE_ADMIN: 'Create Admin',
  CREATE_ICO_PROJECT: 'Create ICO Project',
  SUBMIT_ICO_PROJECT: 'Submit ICO Project',
  EDIT_ICO_PROJECT: 'Edit ICO Project',
  WITHDRAW_ICO_PROJECT: 'Withdraw ICO Project',
  PREVIEW_SPONSORED_ICO_PROJECT: 'Preview Sponsored ICO Project',
  PREVIEW_ANY_ICO_PROJECT: 'Preview Any ICO Project',
  SPONSOR_APPROVE_ICO_PROJECT: 'Approve ICO Project (as Sponsor Firm)',
  SPONSOR_REJECT_ICO_PROJECT: 'Reject ICO Project (as Sponsor Firm)',
  GBX_APPROVE_ICO_PROJECT: 'Approve ICO Project (as ICO Listing Officer)',
  GBX_REJECT_ICO_PROJECT: 'Reject ICO Project (As ICO Listing Officer)',
  ACTIVATE_BACKOFFICE_USER: 'Activate backoffice user',
  DEACTIVATE_BACKOFFICE_USER: 'Deactivate backoffice user',
  MANAGE_SITE_USERS: 'Manage site users',
  ACTIVATE_SITE_USER: 'Activate site user',
  DEACTIVATE_SITE_USER: 'Deactivate site user',
  KYC_VIEW_DETAILS: 'View KYC details',
  KYC_APPROVE_USER: 'Approve KYC for user',
  KYC_REJECT_USER: 'Reject KYC for user',
  KYC_MODIFY_ERC_ADDRESS: 'KYC Modify Contribution Source Address',
  CHANGE_SITE_USER_EMAIL: 'Change site user\'s email',
  EDIT_SITE_USER_DETAILS: 'Edit Site User details',
  CHANGE_USER_IP_ADDRESS: 'Change User IP Address',
  REMOVE_USER_IP_ADDRESS: 'Remove User IP Address',
  EDIT_USER_DETAILS: 'Edit User Details',
  MANAGE_BACKOFFICE_USERS: 'Manage Back-office users',
  MANAGE_ICO_PROJECTS: 'Manage ICO Projects',
  INVITE_TOKEN_ISSUER: 'Invite Token Issuer',
  MANAGE_OWN_TOKEN_ISSUERS: 'Manage Own Token Issuers',
  TOGGLE_ICO_PROJECT_RECOMMENDED_STATE: 'Toggle ICO project recommended state',
  EXPORT_SITE_USER_EXCEL: 'Export site user excel',
};

module.exports = permissions;
