'use strict'
module.exports = {
  NODE_ENV: '"production"',
  VUE_USE_LIVE_API: `"${process.env.VUE_USE_LIVE_API || 'YES'}"`,
  API_ROOT_URL: `"${process.env.API_ROOT_URL || ''}"`,
  MAILCHIMP_POST_URL: `"${process.env.MAILCHIMP_POST_URL || ''}"`,
  GA_SITE_KEY: `"${process.env.GA_SITE_KEY || ''}"`,
  RECAPTCHA_SITE_KEY: `"${process.env.RECAPTCHA_SITE_KEY || '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'}"`,
  ICO_LISTING_ENABLED: `"${process.env.ICO_LISTING_ENABLED || 'NO'}"`,
  PROFILE_ROUTES_ROOT_URL: `"${process.env.PROFILE_ROUTES_ROOT_URL|| ''}"`,
  LISTING_ROUTES_ROOT_URL: `"${process.env.LISTING_ROUTES_ROOT_URL|| ''}"`,
  ICO_LISTING_REDIRECT: `"${process.env.ICO_LISTING_REDIRECT || 'NO'}"`,
  LOGIN_REDIRECT: `"${process.env.LOGIN_REDIRECT || 'NO'}"`,
  FAQ_PAGE_URL: `"${process.env.FAQ_PAGE_URL || ''}"`,
  PROHIBITED_COUNTRY_BUILD: `"${process.env.PROHIBITED_COUNTRY_BUILD || 'NO'}"`,
  TERMS_AND_CONDITIONS_URL: `"${process.env.TERMS_AND_CONDITIONS_URL || ''}"`,
  COOKIE_POLICY_URL: `"${process.env.COOKIE_POLICY_URL || ''}"`,
  PRIVACY_POLICY_URL: `"${process.env.PRIVACY_POLICY_URL || ''}"`,
  TERMS_OF_USE_URL: `"${process.env.TERMS_OF_USE_URL || ''}"`,
  PURCHASE_GUIDE_URL: `"${process.env.PURCHASE_GUIDE_URL || ''}"`,
}
